### ISSUE TITLE
Bare Metal Package order examples not working

### ISSUE THREAD

**Issue by cbreden** [softlayer/softlayer-ruby#112]
Reference: https://github.com/softlayer/softlayer-ruby/blob/master/examples/order_bare_metal_package.rb

The provided package ID of `32` is no longer a valid package, but even after updating the ID to one of the valid ones and choosing a new corresponding, underlying server component for it. I'm still unable to get any package order to verify.  They'll ultimately fail with `The location provided for this order is invalid.`  Haven't determined yet if I'm just unlucky with the vast number of combinations I have tried, or if there's some issue with package order verification at the moment.

For what it's worth, I'm able to verify some cpu/mem combinations for regular non-package orders, but I haven't yet been able to verify a single one via the package system.  One single working combination or example would be nice to see.

**Comment by renier** [comment]
@cbreden, that examples seems to be outdated for various other reasons... 

Can you share the code you are trying? It should be similar to ordering a virtual_guest. Here are some examples:
* https://softlayer.github.io/ruby/createVSI/
* https://softlayer.github.io/ruby/orderLB/
* https://softlayer.github.io/ruby/create_server_from_template/
