### ISSUE TITLE
Exception: object_mask expects strings (ArgumentError)

### ISSUE THREAD

**Issue by rubercuellar** [softlayer/softlayer-ruby#113]
According to: http://sldn.softlayer.com/article/ruby, the object mask should be specified as:

```
object_mask = {
     "hardware" => {
        "operatingSystem" => {
            "passwords" => "",
        },
        "networkComponents" => "",
        "datacenter" => "",
        "processorCount" => ""
    }
}
```

I got the exception: object_mask': object_mask expects strings (ArgumentError)
The code that I tried:

```
require 'softlayer_api'
require 'pp'

user_id = "your user id"
 api_key = "your API key"

object_mask = {"orderItem" => {"order" => {"userRecord" => {"username" =>   ""}}},
"invoiceItem" => {"totalRecurringAmount" => ""}}

billing = SoftLayer::Service.new("SoftLayer_Account",:username => user_id,:api_key => api_key)
user_bill=billing.object_mask(object_mask).getNextInvoiceTopLevelBillingItems

pp user_bill

```
I solved my problem using:
`object_mask = "mask[orderItem[order[userRecord[username]]], invoiceItem[totalRecurringAmount]]"
`
but, this kind of object mask is no longer supported?

**Comment by renier** [comment]
Right, only string object masks are supported since April of 2014, so that article is really old. However, hash-tree object mask could come back with a PR.
