### ISSUE TITLE
VirtualServerUpgradeOrder cannot add additional disks

### ISSUE THREAD

**Issue by ArtsiomMusin** [softlayer/softlayer-ruby#118]
It seems only cores/ram/port speed could be changed by using VirtualServerUpgradeOrder.
How about adding new disks? is there a way to do that?

**Comment by renier** [comment]
@rubercuellar, Is this possible?

**Comment by rubercuellar** [comment]
That's right, it's not possible to add additional disks, The [VirtualServerUpgradeOrder](https://github.com/softlayer/softlayer-ruby/blob/master/lib/softlayer/VirtualServerUpgradeOrder.rb) script only allows to add cores/ram/port speed.
