### ISSUE TITLE
Tags still have referenceCount > 0 after all devices are canceled

### ISSUE THREAD

**Issue by chua-mbt** [softlayer/softlayer-ruby#119]
I have created several devices with a tag [dummy].

I then canceled these machines, so there are no longer any devices listed under the tag [dummy].

In a script, I call getTags through Softlayer's Ruby API.

The list still includes the tag [dummy].

I apply an object mask to get reference counts for tags:

```
{"accountId"=>979273, "id"=>882895, "internal"=>0, "name"=>"dummy", "referenceCount"=>11}
```

Dummy is still being returned, and it's referenceCount is > 0. There seems to be no way to correctly determine which tags have active devices and which tags do not.

**Comment by renier** [comment]
Hi @chua-mbt. This doesn't seem to be an issue with the softlayer-ruby client code itself, but with the SoftLayer API. Have you opened a ticket with them? What did they say?

You can also try posting on stackoverflow tagging the question with _softlayer_.
