### ISSUE TITLE
BareMetal order fails for win 2008 

### ISSUE THREAD

**Issue by ArtsiomMusin** [softlayer/softlayer-ruby#120]
I use BareMetalServerOrder to order a baremetal server. I tried to specify WIN_2008-STD-R2-SP1_64 for the os reference code, but verify failed with:

> Unable to exact match an OS with reference code: WIN_2008-STD-R2-SP1_64. Available options: WIN_2008-STD-R2-SP1_64 

On the portal all windows 2008 options are marked as:

> Windows Server 2008 R2 Standard Edition (64bit) will not be available after 11/23/2016.

But I can select a win 2008 option and verify doesn't complain there. 
So is this an API issue?

**Comment by renier** [comment]
@ArtsiomMusin It might be an issue with the api. Can you run your ruby program using the -d flag `ruby -d ...` and paste the output here?

Also, [check the create options](https://api.softlayer.com/rest/v3/SoftLayer_Virtual_Guest_Block_Device_Template_Group/getVhdImportSoftwareDescriptions.json?objectMask=referenceCode) to make sure it is a valid code.

**Comment by ArtsiomMusin** [comment]
sorry, cannot paste the output here as that code is a part of the huge framework. So no way to simply run it as a ruby script. Anyway, there is an interesting thing. WIN_2008-STD-R2-**SP1**_64 doesn't work, but WIN_2008-STD-R2-**SP2**_64 do!

Looks like the os code for SP1 has some troubles... we haven't tried all os codes, maybe there are more problematic ones, but most of RHEL and CentOS codes are fine as well as win 2012 codes and etc.

**Comment by renier** [comment]
@ArtsiomMusin Ok. you may want to post on stackoverflow about the api issue with windows os codes. Tag it with _softlayer_.

**Comment by ArtsiomMusin** [comment]
done that already: http://stackoverflow.com/questions/40306181/baremetal-order-fails-for-win-2008-sp1
