### ISSUE TITLE
Provide the ability to add datacentres by 'name' (currently its only 'id') for Image templates

### ISSUE THREAD

**Issue by puneetloya** [softlayer/softlayer-ruby#128]
https://github.com/softlayer/softlayer-ruby/blob/master/lib/softlayer/ImageTemplate.rb#L95

The name being unique ('dal01', 'dal05'). Can the API just accept array of datacenter names?

**Comment by renier** [comment]
@puneetloya Yes it does.

**Comment by puneetloya** [comment]
I tried to do image.datacenters = ['dal01', 'dal05']
image being a Sofltayer::ImageTemplate object.
This seem to not work. Can you help me out?

**Comment by renier** [comment]
@puneetloya As the doc says, it has to be an array of SoftLayer::Datacenter instances:

e.g.

```ruby
image.datacenters = ['dal01', 'dal05'].map do |name|
  SoftLayer::Datacenter.datacenter_named(name)
end
```
