### ISSUE TITLE
Support for Family sizes

### ISSUE THREAD

**Issue by greyhoundforty** [softlayer/softlayer-ruby#131]
Wondering if the SoftLayer gem has been updated to support the new [Family Size Virtual Guests](https://www.ibm.com/blogs/bluemix/2017/09/public-virtual-server-families/). 

If not is there a timeline on when this will be supported?

**Comment by smcavallo** [comment]
@greyhoundforty - as far as I know, this functionality was added in https://github.com/softlayer/softlayer-ruby/pull/132

When creating a virtual guest,
To use hvm
```options.supplementalCreateObjectOptions = { bootMode: 'HVM'}
```
To use family sizes
```options.supplementalCreateObjectOptions = { flavorKeyName: 'YOUR_FLAVOR'}
```

This feature has been merged to master - we're just waiting on Softlayer to publish an updated version of the gem to rubygems
