### ISSUE TITLE
Create semantic interface for subnets

### ISSUE THREAD

**Issue by underscorephil** [softlayer/softlayer-ruby#17]

**Comment by paulewog** [comment]
Is this actually going to be implemented?  I can't seem to find any way to get a list of VLANs for a given account using the ruby API.

**Comment by SLsthompson** [comment]
Certainly anything is possible :-).  The Ruby language bindings are a community driven effort with some sponsorship from hobbyists inside of SoftLayer.  At the moment there are no definite plans to add VLAN support to the Ruby client, but I can take this as your feature request.  We also consider and accept suitable pull requests. ;-)

**Comment by paulewog** [comment]
Ah, I see.  I'll see about adding functionality into the softlayer module instead of just local functions and maybe do a pull request if it's decent enough. :)
