### ISSUE TITLE
SoftLayer::ImageTemplate.template_with_global_id method does not return the correct image template

### ISSUE THREAD

**Issue by raulcabero** [softlayer/softlayer-ruby#69]
The SoftLayer::ImageTemplate.template_with_global_id should return an image template object with the specified globalID, but the method returns another image template.

e.g. 
when we make the following call :
image_template =  SoftLayer::ImageTemplate.template_with_global_id("e59000bb-3030-4e38-9249-215524853d9a", client: client)

We got the image template with globalID "29073a7a-2fac-405c-b59f-4de8ad6e4945"

As workaround we need to use the SoftLayer::ImageTemplate.template_with_id method

**Comment by raulcabero** [comment]
I am so sorry for the delay I did not see your update this is the ticket 15660532

Regards

**Comment by SLsthompson** [comment]
Thank you.  I have located the ticket and will see if I can't track down the problem in the Ruby API.

**Comment by SLsthompson** [comment]
I've issued a pull request https://github.com/softlayer/softlayer-ruby/pull/73 which seeks to resolve this issue.  Are you able to create a version based on the commit in that pull request and verify that it resolves the problem for you?
