### ISSUE TITLE
SoftLayer::User_Customer.getPortalLoginToken is unusable without API key

### ISSUE THREAD

**Issue by joshforisha** [softlayer/softlayer-ruby#72]
The getPortalLoginToken method should not require a username or API key in order to be called for authentication, but SoftLayer::Client requires the use of both.

See http://sldn.softlayer.com/reference/services/SoftLayer_User_Customer/getPortalLoginToken

**Comment by SLsthompson** [comment]
Call getPortalLoginToken using a SoftLayer:Service directly:

user_customer = SoftLayer::Service.new("SoftLayer_User_Customer")
result = user_customer.getPortalLoginToken("your-username", "your-password")

**Comment by joshforisha** [comment]
Oh, I didn't even think to try that. Thanks!

However, I still get "A SoftLayer Client requires a username" from the Service.new call.

**Comment by SLsthompson** [comment]
Which version of the softlayer_api gem are you using?

**Comment by joshforisha** [comment]
3.0.0

**Comment by SLsthompson** [comment]
Whoops.  Forgot I had a .softlayer config file.  It's providing the username and API key for me.   Ok.  Let me re-examine.

**Comment by SLsthompson** [comment]
OK.  I can give you workaround, but I'll have to think about the problem in more detail to get a real fix.  You might try this:

mock_client = SoftLayer::Client.new(username: "fake", api_key: "fake")
def mock_client.authentication_headers
  {}
end

service = SoftLayer::Service.new("SoftLayer_User_Customer", client: mock_client)
result = service.getPortalLoginToken("your_username", "your_password").inspect

real_client = SoftLayer::Client.new(username: result["userId"].to_s, api_key: result["hash"])
puts real_client["Account"].getObject

**Comment by joshforisha** [comment]
Thanks, that will work for now.

**Comment by renier** [comment]
Pull request #106 is related

**Comment by renier** [comment]
This has been fixed in #106 .
