### ISSUE TITLE
  TITLE:  The "SoftLayer_Billing_Order_Quote::placeOrder" method fails when try to order a VSI using ruby client

### ISSUE THREAD

**Issue by MiguelHigorre** [softlayer/softlayer-ruby#75]
When trying to order a virtual server instance using the ruby client the "SoftLayer_Billing_Order_Quote::verifyOrder" method fails and raises the following exception:

"A hostname is missing from the order."

The exception is raised despite valid parameters are set and it is possible order using the same quote from UI and also using the php client.

To reproduce the problem use below code

require 'rubygems'

require 'softlayer_api'

require 'pp'

SL_API_USERNAME = "set-me"

SL_API_KEY = "set-me"

client = SoftLayer::Client.new(
:username => "#{SL_API_USERNAME}",
:api_key => "#{SL_API_KEY}")

quoteId = 1242802

order_templates = client['SoftLayer_Billing_Order_Quote'].object_with_id(quoteId).getRecalculatedOrderContainer()

order = order_templates['orderContainers'][0]

order['complexType'] = 'SoftLayer_Container_Product_Order_Virtual_Server'
order['quantity'] = 1
order['location'] = '154820'
order['hardware'] = [{'hostname'=> 'server01', 'domain'=> 'example.com'}]

begin
  receipt = client['SoftLayer_Billing_Order_Quote'].object_with_id(quoteId).placeOrder(order)
  pprint.pprint(receipt)
rescue => error_reason
  puts "The order could not be verified  #{error_reason}"
end

**Comment by renier** [comment]
This also fails from Python and PHP. It's a problem in the api.

You have to do it like this:
```ruby
require 'softlayer_api'

# Credentials to the SoftLayer API are grabbed from the config file by default.
# See https://github.com/softlayer/softlayer-ruby/blob/master/lib/softlayer/Config.rb#L11-L44
client = SoftLayer::Client.new

QUOTE_ID = 1234

quote = client['Billing_Order_Quote'].object_with_id(QUOTE_ID)
order = quote.getRecalculatedOrderContainer['orderContainers'][0]

order['quantity'] = 1
order['virtualGuests'] = [{ 'hostname' => 'quotetest', 'domain' => 'example.com' }]
order.delete('hardware')

pp client['Product_Order'].placeOrder(order)
```
