### ISSUE TITLE
is it possible to apply an advanced filters?

### ISSUE THREAD

**Issue by raulcabero** [softlayer/softlayer-ruby#78]
Hi,

is it possible to apply an advanced filter in the last version of the client? 

for example I would like to set the same object filter as in this REST call
https://$user:$Apikey@api.softlayer.com/rest/v3/SoftLayer_Account/getVirtualGuests.json?objectMask=mask[tagReferences[tag]]&&objectFilter={"virtualGuests":{"tagReferences":{"tag":{"name":{"operation":"in", "options":[{"name": "data", "value": ["_=tagA","_=tagB”]} ] } } } } }}

but I did not find a way how to set the "options" in the Ruby API filter

Regards

**Comment by ju2wheels** [comment]
Yes it is, check out the example used here:
  * https://github.com/softlayer/softlayer-ruby/blob/master/lib/softlayer/VirtualServer.rb#L241-L250

**Comment by SLsthompson** [comment]
Ha!  Thanks.  You beat me to it.

**Comment by raulcabero** [comment]
thank you very much :)
