### ISSUE TITLE
Ordering a BareMetalServer and requesting the object data afterward - how long do I need to wait in between?

### ISSUE THREAD

**Issue by thejohnlin** [softlayer/softlayer-ruby#88]
Between ordering a bare metal instance with ````SoftlayerApiWrapper::BareMetalServerOrder.place_order!```` and ````SoftlayerApiWrapper::BareMetalServer.server_with_id````, what is a decent amount of time to wait? 
 
I'd like to use wait_until_ready on the BareMetalServer object, but come across exceptions when requesting it shortly after placing the order (sleep 15/30/45). With virtual instances, I am able to retrieve the VirtualServer objects immediately after order placement.

**Comment by SLsthompson** [comment]
Bare Metal Server orders often have to go to sales for approval and, depending on the order, may have to be built.  As you are waiting on people, in real life, in either case I don't think one could identify a "decent amount of time to wait".  The concept just doesn't fit the circumstances.

**Comment by thejohnlin** [comment]
I see - I was hoping there might be a way to confirm the order completion with retrieved BareMetalServer object data. Thanks for the clarification.
