### ISSUE TITLE
The SoftLayer_Ticket::addAttachedFile method fails when tried to attach images

### ISSUE THREAD

**Issue by MiguelHigorre** [softlayer/softlayer-ruby#89]
The addAttachedFile method fails when tried to attach images, "No valid authentication headers found. (XMLRPC::FaultException)" exception is raised, 

Requirements:
Ruby 2.1.5
Ruby 2.2.1
SoftLayer API ruby client (3.0.1)

Use below code to reproduce the problem

-----------------------------------------
require 'rubygems'

require 'softlayer_api'

require 'pp'

SL_API_USERNAME = "set-me"
SL_API_KEY = "set-me"
ticket_id = set-me
client = SoftLayer::Client.new(
:username => "#{SL_API_USERNAME}",
:api_key => "#{SL_API_KEY}"
)

x = File.open('/path/to/image.png','rb') { |io| io.read }
fileAttachment = {
  'data'=>x,
  'filename'=>'image.png'
}
result = client['Ticket'].object_with_id(ticket_id).addAttachedFile(fileAttachment)

**Comment by SLsthompson** [comment]
It is my understanding that the file data in this instance should be Base64 encoded.  Could you please try encoding the file data (x in the script above) in Base64 and verify whether or not that allows you to attach the file properly?

**Comment by MiguelHigorre** [comment]
Hello,
After encode the file data, the file was attached to to ticket.

I think the issue can be closed.
