### ISSUE TITLE
ObjectFilter documentation

### ISSUE THREAD

**Issue by ju2wheels** [softlayer/softlayer-ruby#93]
Is there a better source of documentation for the available object filters? There seem to be ones that are available like the "contained_by" one is used heavily in the current implementation for checking if a value is in an array as well as one that I think I saw on the forum a while back for comparing date values that dont have simplified methods in the ObjectFilter class.

In particular im looking for a way of negating matching_ignore_case which doesnt seem to be an option in there without having to do a bunch of code or workaround so im curious if its available and just not documented.

SLDN has data types for the object filters with no docs and the Python implementation has less filters than the ones implemented here.

**Comment by ju2wheels** [comment]
These are the ones that I know that could be currently added:

simplified method name|operation label|operation struct
---------------------------------|--------------------|-----------------------
contained_by|in|```{"operation" => "in", "options" => [{"name" => "data", "value" => string_array }]}```
not_contained_by|not in|```{"operation" => "not in", "options" => [{"name" => "data", "value" => string_array }]}```
between_date|betweenDate|```{"operation" => "betweenDate", "options" => [{"name" => "startDate", "value" => ["03/01/2013 0:0:0"]}, {"name" => "endDate", "value" => ["03/15/2013 23:59:59"]}```

A simple list of operation labels and required options would do if theres no full doc with examples available, this will help us avoid collecting a bunch of data from the API and creating inefficient queries as workarounds.

**Comment by SLsthompson** [comment]
There is not a better source for Object Filter documentation at the moment, though documentation in general, and object filter in specific, has been a topic of much discussion inside of SoftLayer.  I wish I could announce a favorable resolution... but we're not quite there yet.
